---
name: contact-searching
break: true
indent: 4
---

# --> check the Python program
contactsearcher/contactsearcher/main.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountMultipleLineComments --language Python --count 2
    CountSingleLineComments --language Python --count 4

# --> check the Python program
contactsearcher/contactsearcher/search.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "import csv" --count 1 --exact
    MatchFileFragment --fragment "current_contact_job = contact_line[1]" --count 1 --exact
    CountMultipleLineComments --language Python --count 2
    CountSingleLineComments --language Python --count 7

# --> check the Python program
contactsearcher/tests/test_search.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "test_" --count 5
    CountMultipleLineComments --language Python --count 6

# --> check the technical writing for various characteristics
writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 400
    CountMarkdownTags --tag "heading" --count 9
    CountMarkdownTags --tag "code" --count 2
    CountMarkdownTags --tag "code_block" --count 3
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact

# --> check that the number of commits in the Git repository is beyond a threshold
CountCommits --count 5
